### ISSUE TITLE
Who is calling this purge?

### ISSUE THREAD

**Issue by john-nash-rs** [harshitdb3/CacheTTL#2]
https://github.com/harshitdb3/CacheTTL/blob/9e4124f4f4b5cb9612db4c82a92f890ae05f8013/ttlCache.js#L54

**Comment by harshitdb3** [comment]
purge() is called every 1 second by Cache object it self as defined on line 15 ttlCache.js

**Comment by john-nash-rs** [comment]
Looks good to me. Thanks.
